// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
    "github.com/swaggo/swag"
    "io/ioutil"
    "log"
)


// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API Dentshow",
	Description:      "esta api nao tem descricao",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  SwaggerJSON(),
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}


func SwaggerJSON() string {
    file, err := ioutil.ReadFile("./docs/swagger.yaml")

    if err != nil {
        log.Fatal(err)
    }

    text := string(file)
    return text
}